
spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles:
    active: dev
    application:
      name: microservicecloud-config-zhymgc-dev
---
spring:
  profiles:
    active: test
    application:
      name: microservicecloud-config-zhymgc-test